// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDve2O9WgLaQVLCeCi73vNUWkn8UjqOYlQ',
    appId: '1:195037543304:web:6d2c31102315d339b8d83d',
    messagingSenderId: '195037543304',
    projectId: 'flutter-chat-app-4b927',
    authDomain: 'flutter-chat-app-4b927.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4b927.appspot.com',
    measurementId: 'G-Y28R8MX0RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpvmiCofxMLn7JBM-EcmEF_xhtZntkxkA',
    appId: '1:195037543304:android:7077b9f0e18b5485b8d83d',
    messagingSenderId: '195037543304',
    projectId: 'flutter-chat-app-4b927',
    storageBucket: 'flutter-chat-app-4b927.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ja2FEvdp_PmjUtdePk3Wza8ZndqXDGE',
    appId: '1:195037543304:ios:46528a1e0ab10305b8d83d',
    messagingSenderId: '195037543304',
    projectId: 'flutter-chat-app-4b927',
    storageBucket: 'flutter-chat-app-4b927.appspot.com',
    iosClientId: '195037543304-ljliu4ctd9oi1540pn8pc9005huh2ups.apps.googleusercontent.com',
    iosBundleId: 'com.zensar.chat.chatApp',
  );
}
